package runtime

import "time"

// Action is sent by a player/client into a game session.
type Action struct {
	PlayerID string         `json:"player_id"`
	Type     string         `json:"type"`
	Amount   int64          `json:"amount,omitempty"`
	Data     map[string]any `json:"data,omitempty"`
	At       time.Time      `json:"at"`
}

// Event is generated by game adapters and persisted in session logs.
type Event struct {
	Seq       int64          `json:"seq"`
	SessionID string         `json:"session_id"`
	Type      string         `json:"type"`
	PlayerID  string         `json:"player_id,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	At        time.Time      `json:"at"`
}

// Adapter implements game-specific rules while staying transport-agnostic.
type Adapter interface {
	ID() string
	Init(params map[string]any) (any, error)
	ValidateAction(state any, action Action) error
	ApplyAction(state any, action Action) (nextState any, events []Event, err error)
	View(state any, playerID string) (any, error)
}
